// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"strings"
)

// userInitials returns the initials from a name (max 2 chars)
func userInitials(name string) string {
	if name == "" {
		return "?"
	}
	parts := strings.Fields(name)
	if len(parts) == 0 {
		return string(name[0])
	}
	if len(parts) == 1 {
		return strings.ToUpper(string(parts[0][0]))
	}
	return strings.ToUpper(string(parts[0][0]) + string(parts[len(parts)-1][0]))
}

// roleLabel returns Indonesian label for role
func roleLabel(role string) string {
	switch role {
	case "admin":
		return "Administrator"
	case "supervisor":
		return "Supervisor"
	case "consultant":
		return "Konsultan"
	case "finance":
		return "Keuangan"
	case "academic":
		return "Akademik"
	default:
		return role
	}
}

// canAccessFinance returns true if the role can access finance features
func canAccessFinance(role string) bool {
	return role == "admin" || role == "finance"
}

// canAccessAcademic returns true if the role can access academic features
func canAccessAcademic(role string) bool {
	return role == "admin" || role == "academic"
}

// canAccessMarketing returns true if the role can access marketing features
func canAccessMarketing(role string) bool {
	return role == "admin" || role == "supervisor" || role == "consultant"
}

// canAccessReports returns true if the role can access reports
func canAccessReports(role string) bool {
	return role == "admin" || role == "supervisor"
}

// canAccessSettings returns true if the role can access settings
func canAccessSettings(role string) bool {
	return role == "admin"
}

// isSupervisor returns true if the role is supervisor
func isSupervisor(role string) bool {
	return role == "supervisor"
}

// PageData contains common data for all pages
// Note: CSRF protection uses Go 1.25's http.CrossOriginProtection (header-based)
// No token fields needed - uses Sec-Fetch-Site and Origin headers
type PageData struct {
	Title             string
	Version           string
	UserName          string
	UserRole          string
	UnreadSuggestions int // For consultants: count of unread supervisor suggestions
}

func Base(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"id\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 88, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - STMIK Tazkia</title><link rel=\"stylesheet\" href=\"/static/css/output.css\"><script src=\"/static/js/htmx.min.js\" defer></script><script src=\"/static/js/alpine-csp.min.js\" defer></script></head><body class=\"bg-gray-50 min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Portal(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"min-h-screen flex flex-col\"><header class=\"bg-primary-900 text-white shadow-md\" data-testid=\"portal-header\"><div class=\"container mx-auto px-4 py-4 flex items-center justify-between\"><a href=\"/portal\" class=\"text-xl font-bold\" data-testid=\"portal-logo\">STMIK Tazkia</a><nav class=\"flex items-center gap-4\" data-testid=\"portal-nav\"><a href=\"/portal\" class=\"hover:text-secondary-400\" data-testid=\"nav-dashboard\">Dashboard</a> <a href=\"/portal/application\" class=\"hover:text-secondary-400\" data-testid=\"nav-application\">Pendaftaran</a> <a href=\"/portal/documents\" class=\"hover:text-secondary-400\" data-testid=\"nav-documents\">Dokumen</a><form action=\"/logout\" method=\"POST\" class=\"inline\"><button type=\"submit\" class=\"hover:text-secondary-400\" data-testid=\"btn-logout\">Logout</button></form></nav></div></header><main class=\"flex-1 container mx-auto px-4 py-8\" data-testid=\"portal-main\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var3.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</main><footer class=\"bg-gray-100 border-t\" data-testid=\"portal-footer\"><div class=\"container mx-auto px-4 py-4 flex items-center justify-between text-gray-600 text-sm\"><span>&copy; 2025 STMIK Tazkia. All rights reserved.</span> <span class=\"text-gray-400 font-mono text-xs\" title=\"Git commit hash for bug reports\" data-testid=\"version-info\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Version)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 121, Col: 132}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></div></footer></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Admin(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"min-h-screen flex\"><!-- Sidebar --><aside class=\"w-64 bg-primary-900 text-white relative flex-shrink-0\" data-testid=\"admin-sidebar\"><div class=\"p-4 border-b border-primary-800\"><a href=\"/admin\" class=\"text-xl font-bold\" data-testid=\"admin-logo\">PMB Admin</a><p class=\"text-primary-300 text-sm mt-1\">STMIK Tazkia</p></div><nav class=\"mt-2 overflow-y-auto\" style=\"max-height: calc(100vh - 180px);\" data-testid=\"admin-nav\"><a href=\"/admin\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-dashboard\"><span class=\"mr-2\">📊</span> Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if canAccessMarketing(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<a href=\"/admin/my-dashboard\" class=\"block px-4 py-2 hover:bg-primary-800 flex items-center justify-between\" data-testid=\"nav-my-dashboard\"><span><span class=\"mr-2\">🏠</span> Dashboard Saya</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.UnreadSuggestions > 0 {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"bg-yellow-500 text-white text-xs px-2 py-0.5 rounded-full\" data-testid=\"unread-suggestions-badge\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", data.UnreadSuggestions))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 145, Col: 162}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if isSupervisor(data.UserRole) {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<a href=\"/admin/supervisor-dashboard\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-supervisor-dashboard\"><span class=\"mr-2\">👔</span> Dashboard Tim</a>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " <a href=\"/admin/candidates\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-candidates\"><span class=\"mr-2\">👥</span> Kandidat</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessAcademic(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<a href=\"/admin/documents\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-documents\"><span class=\"mr-2\">📄</span> Review Dokumen</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessMarketing(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<a href=\"/admin/announcements\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-announcements\"><span class=\"mr-2\">📣</span> Pengumuman</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessFinance(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"px-4 py-2 text-primary-400 text-xs uppercase tracking-wider mt-4\">Keuangan</div><a href=\"/admin/finance/billings\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-billings\"><span class=\"mr-2\">🧾</span> Tagihan</a> <a href=\"/admin/finance/payments\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-payments\"><span class=\"mr-2\">💳</span> Verifikasi Pembayaran</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessMarketing(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<div class=\"px-4 py-2 text-primary-400 text-xs uppercase tracking-wider mt-4\">Marketing</div><a href=\"/admin/campaigns\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-campaigns\"><span class=\"mr-2\">📢</span> Kampanye</a> <a href=\"/admin/referrers\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-referrers\"><span class=\"mr-2\">🤝</span> Referrer</a> <a href=\"/admin/referral-claims\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-claims\"><span class=\"mr-2\">🔍</span> Klaim Referral</a> <a href=\"/admin/commissions\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-commissions\"><span class=\"mr-2\">💰</span> Komisi</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessReports(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<div class=\"px-4 py-2 text-primary-400 text-xs uppercase tracking-wider mt-4\">Reports</div><a href=\"/admin/reports/funnel\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-funnel\"><span class=\"mr-2\">📈</span> Funnel</a> <a href=\"/admin/reports/consultants\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-consultants\"><span class=\"mr-2\">👤</span> Performa Konsultan</a> <a href=\"/admin/reports/campaigns\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-campaign-roi\"><span class=\"mr-2\">📊</span> ROI Kampanye</a> <a href=\"/admin/reports/referrers\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-referrer-leaderboard\"><span class=\"mr-2\">🏆</span> Leaderboard Referrer</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if canAccessSettings(data.UserRole) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<div class=\"px-4 py-2 text-primary-400 text-xs uppercase tracking-wider mt-4\">Settings</div><a href=\"/admin/settings/users\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-users\"><span class=\"mr-2\">👤</span> Users</a> <a href=\"/admin/settings/programs\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-programs\"><span class=\"mr-2\">🎓</span> Prodi</a> <a href=\"/admin/settings/fees\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-fees\"><span class=\"mr-2\">💵</span> Biaya</a> <a href=\"/admin/settings/rewards\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-rewards\"><span class=\"mr-2\">🎁</span> Reward</a> <a href=\"/admin/settings/categories\" class=\"block px-4 py-2 hover:bg-primary-800\" data-testid=\"nav-categories\"><span class=\"mr-2\">🏷️</span> Kategori</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</nav><div class=\"absolute bottom-0 w-64 p-4 border-t border-primary-800 bg-primary-900\"><div class=\"flex items-center gap-2 mb-2\"><span class=\"w-8 h-8 bg-primary-700 rounded-full flex items-center justify-center text-sm\" data-testid=\"user-avatar\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(userInitials(data.UserName))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 227, Col: 152}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</span><div class=\"text-sm\"><p class=\"font-medium\" data-testid=\"user-name\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(data.UserName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 229, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</p><p class=\"text-primary-400 text-xs\" data-testid=\"user-role\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(roleLabel(data.UserRole))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 230, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</p></div></div><form action=\"/admin/logout\" method=\"POST\" class=\"inline\"><button type=\"submit\" class=\"block text-sm hover:text-secondary-400\" data-testid=\"btn-logout\">Logout</button></form><span class=\"block mt-2 text-primary-400 font-mono text-xs\" title=\"Git commit hash for bug reports\" data-testid=\"version-info\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(data.Version)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 236, Col: 146}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</span></div></aside><!-- Main content --><div class=\"flex-1 flex flex-col min-w-0\"><header class=\"bg-white shadow-sm border-b px-6 py-4\" data-testid=\"admin-header\"><h1 class=\"text-xl font-semibold text-gray-800\" data-testid=\"page-title\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 242, Col: 90}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "</h1></header><main class=\"flex-1 p-6 bg-gray-50 overflow-auto\" data-testid=\"admin-main\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var6.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</main></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Auth(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var14 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var14 == nil {
			templ_7745c5c3_Var14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var15 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div class=\"min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-primary-50 to-secondary-50\" data-testid=\"auth-container\"><div class=\"w-full max-w-md\" data-testid=\"auth-form-container\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var14.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "</div><div class=\"mt-8 text-gray-400 font-mono text-xs\" title=\"Git commit hash for bug reports\" data-testid=\"version-info\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(data.Version)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 259, Col: 18}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var15), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
