export { BasePage } from './BasePage';
export { PortalPage, TestPortalPage } from './PortalPage';
export { AdminPage } from './AdminPage';
export { SettingsUsersPage } from './SettingsUsersPage';
export { SettingsProgramsPage } from './SettingsProgramsPage';
export { SettingsCategoriesPage } from './SettingsCategoriesPage';
export { SettingsFeesPage } from './SettingsFeesPage';
export { SettingsCampaignsPage } from './SettingsCampaignsPage';
export { SettingsRewardsPage } from './SettingsRewardsPage';
export { SettingsReferrersPage } from './SettingsReferrersPage';
export { SettingsAssignmentPage } from './SettingsAssignmentPage';
export { RegistrationPage, LoginPage } from './RegistrationPage';
export { AnnouncementsPage, PortalAnnouncementsPage } from './AnnouncementsPage';
export { CandidatesPage } from './CandidatesPage';
